library(devtools)
packageVersion("devtools")
library(tidyverse)
library(fs)

use_r("fbind")
load_all()
a <- factor(c("character", "hits", "your", "eyeballs"))
b <- factor(c("but", "integer", "where it", "counts"))
fbind(a, b)
